apiVersion: v1
kind: Service
metadata:
  name: my-app-green-service
  labels:
    app: my-app
    environment: green
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31000 # Ensure this is within the valid NodePort range (30000-32767)
  selector:
    app: my-app
    environment: green
